version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net

  app:
    build: ./
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db
    networks:
      - net

volumes:
  postgres_data:

networks:
  net:
    driver: bridge
    external: false
